sonar.projectKey=5h1ro0o_MSPR_BIG_DATA
sonar.organization=5h1ro0o

sonar.projectName=Elections IDF 2022 — ETL & ML Pipeline
sonar.projectVersion=1.0

sonar.sources=etl,ml,config,orchestration,monitoring,db
sonar.tests=tests

sonar.exclusions=\
  ml/artifacts/**,\
  frontend/**,\
  logs/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/*.joblib,\
  **/*.keras,\
  **/*.pkl,\
  **/migrations/**

sonar.test.exclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.11

sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
